[book]
authors = ["txrigxn"]
language = "fr"
src = "src"
title = "Pecunia Documentation"

[output.html]
smart-punctuation = true
mathjax-support = true
site-url = "/pecunia/"
git-repository-url = "https://github.com/Pecunia-App"
hash-files = true

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

